In [2]:
import numpy as np
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [2]:
arr1[2]=5
arr1

array([1, 2, 5])

In [3]:
print(type(arr1))

<class 'numpy.ndarray'>


In [4]:
print(arr1.shape)

(3,)


In [5]:
arr2=np.array([[1,2,3],[3,4,5]])
print(arr2)

[[1 2 3]
 [3 4 5]]


In [6]:
arr2[1][2]

5

In [7]:
print(arr2.shape)

(2, 3)


In [9]:
arr2[1][-1]

5

In [10]:
arrS=np.array(['China','India','US','Mexico'])
arrS

array(['China', 'India', 'US', 'Mexico'], dtype='<U6')

In [12]:
arrR=np.arange(0,20,2)
arrR

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
arrL=np.linspace(0,10,20)
arrL

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [16]:
arr=np.random.rand(10)
arr

array([0.84400025, 0.15972639, 0.17143408, 0.80781035, 0.41128712,
       0.83493892, 0.89402675, 0.1222208 , 0.19291705, 0.69100952])

In [17]:
arr=np.random.rand(3,4)
arr

array([[0.82495829, 0.20318495, 0.24393806, 0.65967517],
       [0.85511796, 0.73772367, 0.01106321, 0.19265978],
       [0.25990272, 0.191453  , 0.30779655, 0.98041785]])

In [20]:
print(np.zeros(10))
print('/n')
print(np.zeros((2,3)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
/n
[[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
print(np.ones((10,10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [24]:
arr = [0, 1, 2]
print(np.repeat(arr,3))

[0 0 0 1 1 1 2 2 2]


In [25]:
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


In [26]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [28]:
arr = np.random.rand(5,5)
arr

array([[0.9048961 , 0.67716006, 0.32365977, 0.7841982 , 0.7348909 ],
       [0.8813766 , 0.96378433, 0.89393044, 0.51230913, 0.71624988],
       [0.65577802, 0.18901502, 0.61460968, 0.53303104, 0.45824212],
       [0.44775708, 0.55333182, 0.74975489, 0.71991722, 0.05309139],
       [0.208129  , 0.76829977, 0.62282055, 0.82976136, 0.57672751]])

In [29]:
np.diag(arr)

array([0.9048961 , 0.96378433, 0.61460968, 0.71991722, 0.57672751])

In [30]:
arr.ndim

2

In [31]:
arr.size

25

In [32]:
arr.shape

(5, 5)

In [33]:
np.random.randint(-10,10,4)

array([  2,   3,  -5, -10])

In [36]:
arr*10

array([[9.04896096, 6.77160062, 3.23659766, 7.84198204, 7.34890905],
       [8.81376596, 9.63784327, 8.93930439, 5.12309132, 7.16249878],
       [6.55778016, 1.89015022, 6.14609677, 5.33031044, 4.58242123],
       [4.47757081, 5.53331817, 7.49754894, 7.19917216, 0.53091392],
       [2.08128997, 7.68299772, 6.2282055 , 8.29761362, 5.76727511]])

In [37]:
np.exp(arr)

array([[2.47167509, 1.96827999, 1.38217696, 2.19064978, 2.08525449],
       [2.41422083, 2.62159871, 2.44471961, 1.66914102, 2.04674326],
       [1.92664089, 1.2080591 , 1.84893478, 1.70408966, 1.58129182],
       [1.56479853, 1.73903753, 2.11648119, 2.05426314, 1.05452602],
       [1.231372  , 2.15609728, 1.86417864, 2.29277153, 1.78020319]])

In [38]:
arr

array([[0.9048961 , 0.67716006, 0.32365977, 0.7841982 , 0.7348909 ],
       [0.8813766 , 0.96378433, 0.89393044, 0.51230913, 0.71624988],
       [0.65577802, 0.18901502, 0.61460968, 0.53303104, 0.45824212],
       [0.44775708, 0.55333182, 0.74975489, 0.71991722, 0.05309139],
       [0.208129  , 0.76829977, 0.62282055, 0.82976136, 0.57672751]])

In [42]:
np.log(arr)

array([[-0.09993515, -0.38984761, -1.12806242, -0.24309348, -0.30803322],
       [-0.12627028, -0.03688774, -0.11212732, -0.66882706, -0.33372618],
       [-0.42193294, -1.66592878, -0.48676788, -0.62917561, -0.78035758],
       [-0.80350442, -0.59179743, -0.28800893, -0.32861905, -2.93574048],
       [-1.56959721, -0.26357529, -0.47349684, -0.18661714, -0.55038538]])

In [43]:
np.sin(arr)

array([[0.78636097, 0.62658223, 0.31803843, 0.70625777, 0.67050622],
       [0.77161525, 0.82135608, 0.7795396 , 0.49019123, 0.65656068],
       [0.60977606, 0.18789155, 0.57663967, 0.50814622, 0.44237227],
       [0.43294481, 0.52552478, 0.6814594 , 0.65932243, 0.05306645],
       [0.20662964, 0.69491362, 0.58332843, 0.7377703 , 0.54528369]])

In [44]:
arr

array([[0.9048961 , 0.67716006, 0.32365977, 0.7841982 , 0.7348909 ],
       [0.8813766 , 0.96378433, 0.89393044, 0.51230913, 0.71624988],
       [0.65577802, 0.18901502, 0.61460968, 0.53303104, 0.45824212],
       [0.44775708, 0.55333182, 0.74975489, 0.71991722, 0.05309139],
       [0.208129  , 0.76829977, 0.62282055, 0.82976136, 0.57672751]])

In [47]:
np.sum(arr,axis=1)

array([3.42480503, 3.96765037, 2.45067588, 2.5238524 , 3.00573819])

In [48]:
np.min(arr,axis=0)

array([0.208129  , 0.18901502, 0.32365977, 0.51230913, 0.05309139])

In [49]:
np.max(arr)

0.9637843266394647

In [51]:
np.mean(arr,axis=1)

array([0.68496101, 0.79353007, 0.49013518, 0.50477048, 0.60114764])

In [52]:
np.std(arr,axis=0)

array([0.26460086, 0.25811165, 0.18843205, 0.13000987, 0.24859144])

In [53]:
np.var(arr)

0.0533913141231095

In [55]:
arr

array([[0.9048961 , 0.67716006, 0.32365977, 0.7841982 , 0.7348909 ],
       [0.8813766 , 0.96378433, 0.89393044, 0.51230913, 0.71624988],
       [0.65577802, 0.18901502, 0.61460968, 0.53303104, 0.45824212],
       [0.44775708, 0.55333182, 0.74975489, 0.71991722, 0.05309139],
       [0.208129  , 0.76829977, 0.62282055, 0.82976136, 0.57672751]])

In [56]:
arr[1:,2:3]

array([[0.89393044],
       [0.61460968],
       [0.74975489],
       [0.62282055]])

In [57]:
 np.sort(arr, axis =1)

array([[0.32365977, 0.67716006, 0.7348909 , 0.7841982 , 0.9048961 ],
       [0.51230913, 0.71624988, 0.8813766 , 0.89393044, 0.96378433],
       [0.18901502, 0.45824212, 0.53303104, 0.61460968, 0.65577802],
       [0.05309139, 0.44775708, 0.55333182, 0.71991722, 0.74975489],
       [0.208129  , 0.57672751, 0.62282055, 0.76829977, 0.82976136]])

In [58]:
 arr.T

array([[0.9048961 , 0.8813766 , 0.65577802, 0.44775708, 0.208129  ],
       [0.67716006, 0.96378433, 0.18901502, 0.55333182, 0.76829977],
       [0.32365977, 0.89393044, 0.61460968, 0.74975489, 0.62282055],
       [0.7841982 , 0.51230913, 0.53303104, 0.71991722, 0.82976136],
       [0.7348909 , 0.71624988, 0.45824212, 0.05309139, 0.57672751]])

In [59]:
arr

array([[0.9048961 , 0.67716006, 0.32365977, 0.7841982 , 0.7348909 ],
       [0.8813766 , 0.96378433, 0.89393044, 0.51230913, 0.71624988],
       [0.65577802, 0.18901502, 0.61460968, 0.53303104, 0.45824212],
       [0.44775708, 0.55333182, 0.74975489, 0.71991722, 0.05309139],
       [0.208129  , 0.76829977, 0.62282055, 0.82976136, 0.57672751]])

In [60]:
arr[:3,:].T

array([[0.9048961 , 0.8813766 , 0.65577802],
       [0.67716006, 0.96378433, 0.18901502],
       [0.32365977, 0.89393044, 0.61460968],
       [0.7841982 , 0.51230913, 0.53303104],
       [0.7348909 , 0.71624988, 0.45824212]])

In [61]:
arr[:3,:].flatten()

array([0.9048961 , 0.67716006, 0.32365977, 0.7841982 , 0.7348909 ,
       0.8813766 , 0.96378433, 0.89393044, 0.51230913, 0.71624988,
       0.65577802, 0.18901502, 0.61460968, 0.53303104, 0.45824212])

In [64]:
arr = np.array([4,5,6,7,8])
arr

array([4, 5, 6, 7, 8])

In [66]:
arr1=np.append(arr,8)
arr1

array([4, 5, 6, 7, 8, 8])

In [67]:
arr2=np.insert(arr, 0,[1,2,3])
arr2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [68]:
arr3=np.delete(arr2,0)
arr3

array([2, 3, 4, 5, 6, 7, 8])

In [69]:
arr3=np.delete(arr2,[1,3])
arr3

array([1, 3, 5, 6, 7, 8])

In [70]:
arrC=arr3.copy()

In [71]:
arrC

array([1, 3, 5, 6, 7, 8])

In [21]:
arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[5,6,7,8],[5,6,7,8]])
arr_cat=np.concatenate((arr1,arr2),axis=1)
print(arr_cat)

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [7]:
catV=np.hstack((arr1,arr2))
catV

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [8]:
catV=np.vstack((arr1,arr2))
catV

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [9]:
arr=np.array([1,2,3,4,5,6,3,6,1,2,4])
np.unique(arr)

array([1, 2, 3, 4, 5, 6])

In [12]:
uniques,counts=np.unique(arr,return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 2 1 2]


In [18]:
#intersection, dufferentiation, neither
arr1=np.array([1,2,3,4,5])
arr2=np.array([3,4,5,6,7])
print(np.intersect1d(arr1,arr2))
print(np.union1d(arr1,arr2))
print(np.setdiff1d(arr1,arr2))

[3 4 5]
[1 2 3 4 5 6 7]
[1 2]
